config/routes.rb
Rails.application.routes.draw do
  resources :pokemons

  root 'search#search'
  
  get 'search/search'

  get 'search/all'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :pokemon
end

app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: [:show, :edit, :update, :destroy]

  # GET /pokemons
  # GET /pokemons.json
  def index
    @pokemons = Pokemon.all
  end

  # GET /pokemons/1
  # GET /pokemons/1.json
  def show
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons
  # POST /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully created.' }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1
  # PATCH/PUT /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully updated.' }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1
  # DELETE /pokemons/1.json
  def destroy
    @pokemon.destroy
    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: 'Pokemon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pokemon_params
      params.require(:pokemon).permit(:number, :name, :element, :description)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @pokemon_all = Pokemon.all
    # Searches for pokemon by name
    # Searches for pokemon by element
    @search_results_element = Pokemon.fuzzy_search(element: params[:search_input])

    if !params[:search_input].nil?
      if params[:search_input].length == 1
        # Searches for pokemon by first letter
        @search_results = Pokemon.where('substr(name, 1, 1) = ? OR substr(name, 1, 1) = ?', params[:search_input].upcase, params[:search_input].downcase)

      # Searches for pokemon by first 2 letters
      elsif params[:search_input].length == 2
        @search_results = Pokemon.where('substr(name, 1, 2) = ? OR substr(name, 1, 2) = ?', params[:search_input], params[:search_input].capitalize)

      # Searches for pokemon by first 3 letters
      elsif params[:search_input].length == 3
        @search_results = Pokemon.where('substr(name, 1, 3) = ? OR substr(name, 1, 3) = ?', params[:search_input], params[:search_input].capitalize)
      else
        @search_results = Pokemon.fuzzy_search(name: params[:search_input])
      end
    end


      if params[:search_input].nil?
        @pokemon_all = Pokemon.all
      end

    render 'search/search.html.erb'
  end

  def all
    @pokemon_all = Pokemon.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pokedex</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src='https://code.responsivevoice.org/responsivevoice.js'></script>
  <link href='https://fonts.googleapis.com/css?family=Bree+Serif' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto:700' rel='stylesheet' type='text/css'>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/pokemons/_form.html.erb
<%= form_for(@pokemon) do |f| %>
  <% if @pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
      <% @pokemon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :element %><br>
    <%= f.text_field :element %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pokemons/edit.html.erb
<h1>Editing Pokemon</h1>

<%= render 'form' %>

<%= link_to 'Show', @pokemon %> |
<%= link_to 'Back', pokemons_path %>

app/views/pokemons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pokemons</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Name</th>
      <th>Element</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pokemons.each do |pokemon| %>
      <tr>
        <td><%= pokemon.index_number %></td>
        <td><%= pokemon.name %></td>
        <td><%= pokemon.element %></td>
        <td><%= pokemon.description %></td>
        <td><%= link_to 'Show', pokemon %></td>
        <td><%= link_to 'Edit', edit_pokemon_path(pokemon) %></td>
        <td><%= link_to 'Destroy', pokemon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pokemon', new_pokemon_path %>

app/views/pokemons/new.html.erb
<h1>New Pokemon</h1>

<%= render 'form' %>

<%= link_to 'Back', pokemons_path %>

app/views/pokemons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @pokemon.number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @pokemon.name %>
</p>

<p>
  <strong>Element:</strong>
  <%= @pokemon.element %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pokemon.description %>
</p>

<%= link_to 'Edit', edit_pokemon_path(@pokemon) %> |
<%= link_to 'Back', pokemons_path %>

app/views/search/all.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1>Pokemon Index</h1>
    <form action="search" method="get">
      <input class="search_bar" type="text" name="search_input" placeholder="Name or Type"/>
      <button class="search_bar" class="submit">Search</button>
    </form>
    <a class="all_pokemon" href="/search/all">All Pokemon</a>
  </div>
</div>

<table class="table">
  <thead>

  </thead>
  <tbody>

  <% @pokemon_all.each do |pokemon| %>
    <tr class="<%= pokemon.color %> panel panel-default">
      <td><%= pokemon.index_number %></td>
      <td><img class="pokemon_picture" src="<%= pokemon.picture %>"</td>
      <td>
        <h3><%= pokemon.name %></h3>
        <h4><%= pokemon.element %></h4>
        <br>
        <p><%= pokemon.description %></p>
      </td>
      <td>
        <input onclick='responsiveVoice.speak("<%= escape_javascript pokemon.description %>");' type='button' value='🔊 Play' />
      </td>
    </tr>
  <% end %>

  </tbody>
</table>

app/views/search/search.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1>Pokemon Index</h1>
    <form action="search" method="get">
      <input class="search_bar" type="text" name="search_input" placeholder="Name or Type"/>
      <button class="search_bar" class="submit">Search</button>
    </form>
    <a class="all_pokemon" href="/search/all">All Pokemon</a>
  </div>
</div>

<table class="table">
  <thead>

  </thead>
  <tbody>

    <% if !@search_results_element.nil? %>
      <% @search_results_element.each do |pokemon| %>
        <tr class="<%= pokemon.color %> panel panel-default">
          <td><%= pokemon.index_number %></td>
          <td><img class="pokemon_picture" src="<%= pokemon.picture %>"</td>
          <td>
            <h3><%= pokemon.name %></h3>
            <h4><%= pokemon.element %></h4>
            <br>
            <p><%= pokemon.description %></p>
          </td>
          <td>
            <input onclick='responsiveVoice.speak("<%= escape_javascript pokemon.description %>");' type='button' value='🔊 Play' />
          </td>
        </tr>
      <% end %>
    <% end %>

    <% if !@search_results.nil? %>
      <% @search_results.each do |pokemon| %>
        <tr class="<%= pokemon.color %> panel panel-default">
          <td><%= pokemon.index_number %></td>
          <td><img class="pokemon_picture" src="<%= pokemon.picture %>"</td>
          <td>
            <h3><%= pokemon.name %></h3>
            <h4><%= pokemon.element %></h4>
            <br>
            <p><%= pokemon.description %></p>
          </td>
          <td>
            <input onclick='responsiveVoice.speak("<%= escape_javascript pokemon.description %>");' type='button' value='🔊 Play' />
          </td>
        </tr>
      <% end %>
    <% end %>

  <% if params[:search_input] == "all" %>
    <% @pokemon_all.each do |pokemon| %>
      <tr class="<%= pokemon.color %> panel panel-default">
        <td><%= pokemon.index_number %></td>
        <td><img class="pokemon_picture" src="<%= pokemon.picture %>"</td>
        <td>
          <h3><%= pokemon.name %></h3>
          <h4><%= pokemon.element %></h4>
          <br>
          <p><%= pokemon.description %></p>
        </td>
        <td>
          <input onclick='responsiveVoice.speak("<%= escape_javascript pokemon.description %>");' type='button' value='🔊 Play' />
        </td>
      </tr>
    <% end %>
  <% end %>

  </tbody>
</table>